name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: بررسی کد
        uses: actions/checkout@v3
      
      - name: تنظیم Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: نصب وابستگی‌ها
        run: npm ci
      
      - name: ساخت پروژه
        run: npm run build
      
      - name: راه‌اندازی GitHub Pages
        uses: actions/configure-pages@v3
      
      - name: آپلود آرتیفکت
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: استقرار در GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
